use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use log::{info, warn, debug};
use thiserror::Error;

use crate::config::GpuMode;

#[derive(Error, Debug)]
pub enum GpuError {
    #[error("IO Error: {0}")]
    Io(#[from] std::io::Error),
    #[error("Command execution failed: {0}")]
    CommandFailed(String),
    #[error("dGPU not found: {0}")]
    DeviceNotFound(String),
}

const BLACKLIST_FILE_PATH: &str = "/etc/modprobe.d/hw-control-gpu.conf";

/// Scan /sys/bus/pci/devices/ to find the dedicated GPU's PCI address (e.g. 0000:01:00.0).
/// Looks for NVIDIA (0x10de) or AMD (0x1002) 3D/VGA controllers that are NOT the boot VGA device.
pub fn find_dgpu_pci_address() -> Option<String> {
    let pci_dir = Path::new("/sys/bus/pci/devices");
    if !pci_dir.exists() {
        warn!("PCI devices sysfs directory {:?} does not exist. Running on non-Linux or mock environment?", pci_dir);
        return None;
    }

    if let Ok(entries) = fs::read_dir(pci_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if let Some(pci_id) = path.file_name().and_then(|n| n.to_str()) {
                let vendor_path = path.join("vendor");
                let class_path = path.join("class");
                
                if vendor_path.exists() && class_path.exists() {
                    let vendor = fs::read_to_string(vendor_path).unwrap_or_default().trim().to_lowercase();
                    let class = fs::read_to_string(class_path).unwrap_or_default().trim().to_lowercase();

                    let is_nvidia = vendor == "0x10de";
                    let is_amd = vendor == "0x1002";
                    let is_display_or_3d = class.starts_with("0x0300") || class.starts_with("0x0302");

                    if (is_nvidia || is_amd) && is_display_or_3d {
                        // Check if it's NOT the boot VGA (primary iGPU)
                        let boot_vga_path = path.join("boot_vga");
                        let is_boot_vga = if boot_vga_path.exists() {
                            fs::read_to_string(boot_vga_path).unwrap_or_default().trim() == "1"
                        } else {
                            false
                        };

                        if !is_boot_vga {
                            debug!("Found dGPU at {} (vendor={}, class={})", pci_id, vendor, class);
                            return Some(pci_id.to_string());
                        }
                    }
                }
            }
        }
    }
    None
}

/// Recursively find a WMI file (like dgpu_disable or gpu_mux) under /sys/devices/platform/
pub fn find_wmi_file(name: &str) -> Option<PathBuf> {
    let platform_dir = Path::new("/sys/devices/platform");
    if !platform_dir.exists() {
        debug!("Platform sysfs directory {:?} does not exist.", platform_dir);
        return None;
    }

    if let Ok(entries) = fs::read_dir(platform_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                // Check direct child
                let file_path = path.join(name);
                if file_path.exists() {
                    return Some(file_path);
                }
                // Check subdirs (like asus-nb-wmi/)
                if let Ok(sub_entries) = fs::read_dir(&path) {
                    for sub_entry in sub_entries.flatten() {
                        let sub_path = sub_entry.path();
                        if sub_path.file_name().map_or(false, |n| n == name) {
                            return Some(sub_path);
                        }
                    }
                }
            }
        }
    }
    None
}

/// Apply blacklisting of NVIDIA and nouveau drivers.
pub fn set_blacklist(blacklist: bool) -> Result<(), GpuError> {
    let path = Path::new(BLACKLIST_FILE_PATH);
    if blacklist {
        info!("Writing GPU driver blacklist to {}", BLACKLIST_FILE_PATH);
        let content = "\
# Generated by hw-control
blacklist nvidia
blacklist nvidia_drm
blacklist nvidia_modeset
blacklist nvidia_uvm
blacklist nouveau
blacklist amdgpu
";
        // Create parent directories if they don't exist
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(path, content)?;
    } else {
        if path.exists() {
            info!("Removing GPU driver blacklist at {}", BLACKLIST_FILE_PATH);
            fs::remove_file(path)?;
        }
    }
    Ok(())
}

/// Unload a list of kernel modules in order.
pub fn unload_modules(modules: &[&str]) -> Result<(), GpuError> {
    for &module in modules {
        info!("Attempting to unload kernel module: {}", module);
        let output = Command::new("modprobe")
            .arg("-r")
            .arg(module)
            .output();

        match output {
            Ok(out) => {
                if out.status.success() {
                    info!("Successfully unloaded module: {}", module);
                } else {
                    let err_msg = String::from_utf8_lossy(&out.stderr).trim().to_string();
                    if err_msg.contains("not found") || err_msg.contains("is not loaded") {
                        debug!("Module {} was not loaded anyway.", module);
                    } else {
                        warn!("Failed to unload module {}: {}", module, err_msg);
                        // We continue unloading other modules even if one fails
                    }
                }
            }
            Err(e) => {
                warn!("Command 'modprobe -r {}' failed: {}", module, e);
            }
        }
    }
    Ok(())
}

/// Load a list of kernel modules in order.
pub fn load_modules(modules: &[&str]) -> Result<(), GpuError> {
    for &module in modules {
        info!("Attempting to load kernel module: {}", module);
        let output = Command::new("modprobe")
            .arg(module)
            .output();

        match output {
            Ok(out) => {
                if out.status.success() {
                    info!("Successfully loaded module: {}", module);
                } else {
                    let err_msg = String::from_utf8_lossy(&out.stderr).trim().to_string();
                    warn!("Failed to load module {}: {}", module, err_msg);
                }
            }
            Err(e) => {
                warn!("Command 'modprobe {}' failed: {}", module, e);
            }
        }
    }
    Ok(())
}

/// Unbind the dGPU from its driver.
pub fn unbind_dgpu(pci_id: &str) -> Result<(), GpuError> {
    let driver_path = PathBuf::from(format!("/sys/bus/pci/devices/{}/driver", pci_id));
    if driver_path.exists() {
        let unbind_path = driver_path.join("unbind");
        info!("Unbinding dGPU {} from driver", pci_id);
        if unbind_path.exists() {
            fs::write(&unbind_path, pci_id)?;
            info!("Successfully unbound dGPU {} from driver", pci_id);
        } else {
            warn!("Driver unbind path {:?} does not exist", unbind_path);
        }
    } else {
        debug!("dGPU {} has no active driver bound", pci_id);
    }
    Ok(())
}

/// Trigger a rescan of the PCI bus to redetect the dGPU.
pub fn trigger_pci_rescan() -> Result<(), GpuError> {
    let rescan_path = Path::new("/sys/bus/pci/rescan");
    if rescan_path.exists() {
        info!("Triggering PCI bus rescan");
        fs::write(rescan_path, "1")?;
    } else {
        warn!("PCI rescan path {:?} does not exist. Cannot trigger rescan.", rescan_path);
    }
    Ok(())
}

/// Set the PCI power management control and d3cold options.
pub fn set_pci_power_control(pci_id: &str, control: &str, d3cold: Option<&str>) -> Result<(), GpuError> {
    let power_dir = PathBuf::from(format!("/sys/bus/pci/devices/{}/power", pci_id));
    if !power_dir.exists() {
        warn!("PCI power directory {:?} does not exist for GPU {}", power_dir, pci_id);
        return Ok(());
    }

    let control_path = power_dir.join("control");
    if control_path.exists() {
        info!("Setting PCI power control for {} to {}", pci_id, control);
        fs::write(control_path, control)?;
    } else {
        warn!("PCI power control path {:?} does not exist", control_path);
    }

    if let Some(d3) = d3cold {
        let d3cold_path = power_dir.join("d3cold_allowed");
        if d3cold_path.exists() {
            info!("Setting PCI d3cold_allowed for {} to {}", pci_id, d3);
            fs::write(d3cold_path, d3)?;
        } else {
            warn!("PCI d3cold_allowed path {:?} does not exist", d3cold_path);
        }
    }

    Ok(())
}

/// Power down the dGPU by writing "1" to its PCI remove file.
pub fn remove_pci_device(pci_id: &str) -> Result<(), GpuError> {
    let remove_path = PathBuf::from(format!("/sys/bus/pci/devices/{}/remove", pci_id));
    if remove_path.exists() {
        info!("Removing PCI device {} to trigger power-down", pci_id);
        fs::write(remove_path, "1")?;
        info!("Successfully wrote to remove path for {}", pci_id);
    } else {
        warn!("PCI remove path for GPU {} does not exist", pci_id);
    }
    Ok(())
}

/// Toggle WMI platform dgpu_disable (0 = enable, 1 = disable).
pub fn set_wmi_dgpu_disable(disabled: bool) -> Result<(), GpuError> {
    if let Some(path) = find_wmi_file("dgpu_disable") {
        let val = if disabled { "1" } else { "0" };
        info!("Writing {} to WMI dgpu_disable path {:?}", val, path);
        fs::write(&path, val)?;
    } else {
        debug!("WMI dgpu_disable path not found on this system.");
    }
    Ok(())
}

/// Toggle WMI platform gpu_mux (0 = Hybrid, 1 = Dedicated).
pub fn set_wmi_gpu_mux(dedicated: bool) -> Result<(), GpuError> {
    if let Some(path) = find_wmi_file("gpu_mux") {
        let val = if dedicated { "1" } else { "0" };
        info!("Writing {} to WMI gpu_mux path {:?}", val, path);
        fs::write(&path, val)?;
    } else {
        debug!("WMI gpu_mux path not found on this system.");
    }
    Ok(())
}

/// High-level function to transition the system to a new GPU mode.
pub fn switch_gpu_mode(mode: GpuMode) -> Result<(), GpuError> {
    info!("Transitioning GPU mode to: {}", mode);

    let modules_to_unload = ["nvidia_drm", "nvidia_modeset", "nvidia_uvm", "nvidia", "nouveau"];
    let modules_to_load = ["nvidia", "nvidia_uvm", "nvidia_modeset", "nvidia_drm"];

    match mode {
        GpuMode::Integrated => {
            // 1. Unbind and unload modules
            if let Some(pci_id) = find_dgpu_pci_address() {
                let _ = unbind_dgpu(&pci_id);
            } else {
                info!("No dGPU found, skipping driver unbind.");
            }

            let _ = unload_modules(&modules_to_unload);

            // 2. Set blacklist so drivers won't load on boot/demand
            set_blacklist(true)?;

            // 3. WMI disable if supported
            let _ = set_wmi_dgpu_disable(true);

            // 4. Force PCI power down or remove device
            if let Some(pci_id) = find_dgpu_pci_address() {
                let _ = set_pci_power_control(&pci_id, "auto", Some("1"));
                let _ = remove_pci_device(&pci_id);
            }
            info!("GPU successfully configured for Integrated mode.");
        }
        GpuMode::Hybrid => {
            // 1. Remove blacklist
            set_blacklist(false)?;

            // 2. Enable in WMI
            let _ = set_wmi_dgpu_disable(false);
            let _ = set_wmi_gpu_mux(false); // Hybrid/Optimus

            // 3. Rescan PCI bus to wake/rediscover the GPU if it was removed
            trigger_pci_rescan()?;

            // 4. Try to find the device again and configure power saving
            if let Some(pci_id) = find_dgpu_pci_address() {
                // For hybrid, we allow it to power down dynamically (auto)
                let _ = set_pci_power_control(&pci_id, "auto", Some("1"));
            } else {
                warn!("dGPU not visible on PCI bus after rescan.");
            }

            // 5. Load modules
            let _ = load_modules(&modules_to_load);
            info!("GPU successfully configured for Hybrid mode.");
        }
        GpuMode::Dedicated => {
            // 1. Remove blacklist
            set_blacklist(false)?;

            // 2. Enable in WMI and toggle hardware MUX to dedicated
            let _ = set_wmi_dgpu_disable(false);
            let _ = set_wmi_gpu_mux(true); // Dedicated/MUXed

            // 3. Rescan PCI bus
            trigger_pci_rescan()?;

            // 4. Set power control to "on" to prevent suspension in Dedicated mode
            if let Some(pci_id) = find_dgpu_pci_address() {
                let _ = set_pci_power_control(&pci_id, "on", Some("0"));
            } else {
                warn!("dGPU not visible on PCI bus after rescan.");
            }

            // 5. Load modules
            let _ = load_modules(&modules_to_load);
            info!("GPU successfully configured for Dedicated mode.");
        }
    }

    Ok(())
}
